### ISSUE TITLE
JavaScript Example

### ISSUE THREAD

**Issue by dmlowery** [manifestinteractive/weather-underground-icons#1]
#### Overview:

Can you please provide an example on how to use these icons with the Weather Underground JSON using JavaScript? Thank you!

**Comment by manifestinteractive** [comment]
Example Created and posted to Master.

https://github.com/manifestinteractive/weather-underground-icons/tree/master/example

I have added a section to the README file:

https://github.com/manifestinteractive/weather-underground-icons/blob/master/README.md#using-the-example

**Comment by manifestinteractive** [comment]
Example in use

![example-small](https://cloud.githubusercontent.com/assets/508411/20203888/04d9e57c-a799-11e6-9879-b93dbc834bb5.gif)

**Comment by manifestinteractive** [comment]
Moved Demo App to its own repo and updated the docs to reflect the changes.

https://github.com/manifestinteractive/weather-underground-app
