### ISSUE TITLE
Night version of icons

### ISSUE THREAD

**Issue by tschaefer** [manifestinteractive/weather-underground-icons#2]
Hi,

very nice set of Wunderground icons, would be very nice to have a night version, moon instead of sun.
Maybe you've got the muse to create them. :man_dancing: 

Cheers.

**Comment by tschaefer** [comment]
Oh, just saw the icons haven't be done by you. Sorry for the noise ...

**Comment by manifestinteractive** [comment]
@tschaefer Yep, sadly I am not the awesome designer that made these.  But I did get her permission to port them over to something us developers can use.  I do like the idea of this though so I am going to re-open the issue in case anyone in the community wants to tackle this.

I think editing the SVG files should be pretty straight forward and you could just swap out the moon for the sun in some cases, would still be a bit of work, but totally doable.

**Comment by manifestinteractive** [comment]
@tschaefer what are your thoughts on how the day/night icons could be organized in this project?  You thinking separate folders ( eg `day/clear.png` `night/clear.png` ) or maybe a name suffix ( eg `clear-day.png` `clear-night.png` )  ?

**Comment by tschaefer** [comment]
@manifestinteractive I would prefer to put the day/night icons in seperate folders. I'm using exclusive the icons for my menubar ([tint2](https://gitlab.com/o9000/tint2)) in WM Openbox, see [screenshot](https://sau.frubar.net/shots/39156.png).

**Comment by 7ooL** [comment]
i'd also like to see night versions

**Comment by cawa-93** [comment]
+1

**Comment by lorol** [comment]
+1, 
As for the night names, you can use "nt_" prefix like WunderGround approach.
In fact only 2 new "night" icons + some logic how you pick others on day/night condition, can cover simplistically the need:

1)     nt_mostlycloudy = nt_mostlysunny = nt_partlycloudy = nt_partlysunny
2)     nt_sunny = nt_clear

**Comment by W0CHP** [comment]
👍 +1

[This project](https://github.com/erikflowers/weather-icons) implements icons for night.
However, I like _this_ project's simple implementation, prefer its icons, and would _love_ night icons.

I wish I could help in some way, but I can barely draw a stick figure :-/

**Comment by manifestinteractive** [comment]
Question for those interested in this issue.  I am going to be working on a personal project that would benefit from these night time icons as well and wondering how we should handle the moon design.

While we could easily just make a simple round moon, my thoughts are that we also have an opportunity to represent the phases of the moon.

Seems like if the sky is `clear` and we are using night time icons, we could hit the [astronomy](https://www.wunderground.com/weather/api/d/docs?d=data/astronomy) API endpoint to figure out the current phase of the moon.

I would love to hear everyones thoughts on what "night version" truly means, as IMO it's more complex than just swapping out the sun for a moon.

**Comment by lorol** [comment]
Hi, @manifestinteractive 
IMO, night addition should be simplistic and compatible to the nice set you already made. 
Just to correspond to [WU sets and names](https://www.wunderground.com/weather/api/d/docs?d=resources/icon-sets) 
If you want to complicate it with detailed moon states, please do this in separate group.

**Comment by 7ooL** [comment]
some time ago i just made some variants of night icons off this project for my needs. i have them posted here. I only ever did .png images in 64x64 and 128x128, there was only about 6 images that had the sun swapped for the moon for each size. 
https://github.com/7ooL/Weather-Underground-Icons

**Comment by W0CHP** [comment]
@manifestinteractive
Cool idea for another astrological project I’m working on using PyEphem, but for the sake of displaying simple WX conditions at night while leveraging the existing “nt_” api responses, I fully agree with @lorol.

**Comment by manifestinteractive** [comment]
Here is what I am working on, should have committed in an hour or so:

![icon-preview](https://user-images.githubusercontent.com/508411/33246944-4b24d5b6-d2e8-11e7-9e69-8d5609c73a1c.png)
![icon-preview](https://user-images.githubusercontent.com/508411/33246946-4e61f63c-d2e8-11e7-964b-446899d4228d.png)

**Comment by lorol** [comment]
Not sure but IMO a generic moon should look something like this:
![moon](https://user-images.githubusercontent.com/4274080/33248206-c2a66128-d2f1-11e7-8d62-18dacb6ff23a.png)

**Comment by manifestinteractive** [comment]
@lorol I'm always partial to the full moon, but yes, the most common representation is what you provided.  I will make that update on the three images.  I'm also packing up a solid color version of each as well, as I have had a need for these icons as either all black, or all white, with none of the blue / yellow stuff in it.

**Comment by lorol** [comment]
:) in this case, you can make the moon just very-very slightly bitten either left or right upper side, like the apple symbol.  
It may look very nice.

**Comment by lorol** [comment]
@manifestinteractive, here is the (almost) full nt_ name list from the API.
Hope it will bring you some idea of what else is worth to be in a separate icon, what can be merged within nt's and what with dailies:

nt_chanceflurries
nt_chancerain
nt_chancesleet
nt_chancesnow
nt_chancetstorms
nt_clear
nt_cloudy
nt_flurries
nt_fog
nt_hazy
nt_mostlycloudy
nt_mostlysunny
nt_partlycloudy
nt_partlysunny
nt_sleet
nt_rain
nt_snow
nt_sunny  :) 
nt_tstorms

**Comment by manifestinteractive** [comment]
ah, so since most of these are going to be the exact same icon, are you wanting them duplicated ?  If so, I will need to spend several more hours on this, not so much that making the icons is hard, just the updating the CSS, docs, demo app, etc ... all that gets factored in with the change.  So if we can agree that the crescent moon shape you provided is ideal, and that we need an `nt_` prefix for each icon, that sets the acceptance criteria for me to wrap this up.

**Comment by manifestinteractive** [comment]
@lorol Can I get your feedback on these three icons ?

![nt_clear](https://user-images.githubusercontent.com/508411/33250347-f47da376-d2fd-11e7-94dd-47b8f639ed8b.png)
![nt_mostlycloudy](https://user-images.githubusercontent.com/508411/33250348-f48b2f96-d2fd-11e7-9859-f5076895b3f1.png)
![nt_mostlysunny](https://user-images.githubusercontent.com/508411/33250349-f4976234-d2fd-11e7-97d3-b0b03a9760a2.png)

**Comment by manifestinteractive** [comment]
This issue is now resolved with the release of v1.0.1 which is currently in the master branch.  If there are any requested changes to these new night time icons, let's open a new issue :)

**Comment by W0CHP** [comment]
Looks perfect and thank you @manifestinteractive!

**Comment by lorol** [comment]
I like them, too! Thank you.
